services:
  - type: web
    name: ton-cerveau-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ACCESS_TOKEN
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false